/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:Translator:452170:
  println("Translator - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:Translator:452170:

public void textfield1_change2(GTextField source, GEvent event) { //_CODE_:textfield1:533689:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield1:533689:

public void button1_click1(GButton source, GEvent event) { //_CODE_:Spill_Lyd:298513:
  println("Spill_Lyd - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Spill_Lyd:298513:

public void button1_click2(GButton source, GEvent event) { //_CODE_:Translate:812644:
  println("Translate - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Translate:812644:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  Translator = new GTextField(this, 127, 60, 304, 113, G4P.SCROLLBARS_NONE);
  Translator.setPromptText("Indsæt din tekst eller morsekode her");
  Translator.setOpaque(true);
  Translator.addEventHandler(this, "textfield1_change1");
  textfield1 = new GTextField(this, 128, 229, 120, 30, G4P.SCROLLBARS_NONE);
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change2");
  Spill_Lyd = new GButton(this, 128, 188, 80, 30);
  Spill_Lyd.setText("Spill Lyd");
  Spill_Lyd.addEventHandler(this, "button1_click1");
  Translate = new GButton(this, 299, 188, 80, 30);
  Translate.setText("Translate");
  Translate.addEventHandler(this, "button1_click2");
}

// Variable declarations 
// autogenerated do not edit
GTextField Translator; 
GTextField textfield1; 
GButton Spill_Lyd; 
GButton Translate; 
